apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: contosouniversitydb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: contosouniversitydb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: contosouniversitydb
        image: microsoft/mssql-server-linux:2017-CU3
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          value: "<YourStrong!Passw0rd>"
---
apiVersion: v1
kind: Service
metadata:
  name: contosouniversitydb
spec:
  selector:
    app: contosouniversitydb
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer